#! /bin/bash

### XXX this file is automatically generated via puppet ! Do not alter it manually !

CPP_DIR="/srv/dev/cpp"
CPP_SHARED_DIR="/srv/dev/cpp/shared"
CPP_SHARED_ARCHIVES_DIR="/srv/dev/cpp/shared/archives"
CPP_SHARED_SRC_DIR="/srv/dev/cpp/shared/src"
CPP_SHARED_SCRIPTS_DIR="/srv/dev/cpp/shared/scripts"

CPP_ENV_DEF_FILE="cpp_deploy_env.sh"
CPP_TARGET_DEF_FILE_RADIX="cpp_deploy_target_"
